# Week 3 {#week3}

In week 3 of the course, you will focus on how the environment alters community dynamics. This week of the course will be taught by [Duygu Tolunay](https://www.uu.nl/medewerkers/DTolunay)! Duygu is a PhD student working with Mariet Hefting in the Ecology and Biodiversity group who focuses on peat! 

*Just a reminder: this week is almost completely in person so please come to class in person!* 

This week's checklist:  
- [  ]Turn in R assignment 4 - Day 8 - Modeling the Environment can be found on Teams, on Blackboard, or in your email!   
- [  ]Work together as a group on your presentations for Duygu's assignment

## Day 7 - 9. May 2022 

**Location:** Koningsbergergebouw Atlas  
**Time:** 11:00-12:45  

Plan -  
1. Introduction - overview of the week   
2. Organic matter and decomposition   
3. Introduction of peatlands   

## Day 8 - 11. May 2022

**Location:** Androclusgebouw C101   
**Time:** 11-12:45   

Plan -   
1. The effect of abiotic elements on microbial activity   
  - Oxygen availability/water content   
  - Temperature and pH   
  - Litter quality   
  - Nutrients   

In the afternoon, you should work on the R assignment for the week in your designated work room: BBG 161,165, or 223. Katie will also stop by to solve R problems. :)

You can find the explanation for this week's short modeling assignment [here](https://youtu.be/tvEakJujUw4)  

The R markdown file is on the Teams site and the blackboard and can be submitted via Blackboard.   

*Also planned* - 
Working on article research and reading  
Discussing in your groups and preparing presentations     

## Day 9 - 13. May 2022 

*Friday morning*  
**Online lecture via the TEAMS**   
Ecosystem services of peatlands in the NL  
Threats to peatlands   


*Friday afternoon*  
**Location:** Ruppertgebouw 040    
**Time:** 13:15-15:30  

Group presentations   
Summary of the week   

