# Week 5 {#week5}

In week 5 of the course, we are going from communities to META communities and applying meta-community ecology to active restoration! 

This week's checklist:   
[  ] Read Chase et al. 2020 - Biodiversity conservation through the lens of metacommunity ecology - it is in the files on the Teams site   
[  ]Turn in the theory assignment for the week   
[  ]Start to read the synopsis of the [IPBES/IPCC joint report](https://zenodo.org/record/5101125#.YoeUzOxBz0o) for Week 7 of the course   
[  ]Start to read the [summary for policy makers of the IPBES Report](https://zenodo.org/record/3553579#.YoeV1uxBz0o)   
[  ]Make a list of at least five recommendations that are based on the theories that we've discussed in class   

This week (like last) can be very clearly structured into two parts:   
1. **Theory**  
2. **Application**  

## Day 13 - 23.5.2022 - Theory 
The theory lecture can be found [here](https://youtu.be/p3X1zmvvpbc) but will also be given live on Monday!    

You can also find the explanation for this week's modeling components [here](https://youtu.be/rRMcHc3LSuc).      

**BY WEDNESDAY** Read Chase et al. 2020 Biodiversity conservation through the lens of metacommunity ecology    

**BY THE END OF THE WEEK** - Complete the modeling assignment on meta-communities which you can find on the Blackboard, in Teams, or in your email! It should be turned in via Teams.       

## Day 14 - 25.5.2022 - Application 

Join live online via the Teams for a lecture and discussion by [Dr. Emma Ladouceur](https://www.idiv.de/en/profile/888.html), head of the [Global Restore Project](https://www.globalrestoreproject.com/) who will talk about how meta-community ecology inspires her work on ecosystem restoration. The lecture will be recorded live and the recording and slides will be available after the lecture.   

## Day 15 - 27.5.2022 - NO CLASS **HOLIDAY** 


